# Generated by Django 3.0.6 on 2020-05-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_desc', models.TextField()),
                ('product_category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('added_date', models.DateField()),
                ('image', models.ImageField(upload_to='shop/products_images')),
            ],
        ),
    ]
