# Generated by Django 3.0.6 on 2020-06-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0003_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
