# Generated by Django 3.0.6 on 2020-06-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0004_auto_20200607_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_before',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, null=True),
        ),
    ]
